### ISSUE TITLE
Shape around date on Article Cover page

### ISSUE THREAD

**Issue by rbsingh13** [HarveySheppard/yLaTeX#12]
Hello Mr. Sheppard,

Thanks again for such phenomenal work related to different templates.  I enjoy using them and modifying for my personal use. 

I downloaded your latest repository and in the PDF example for the Articles template, there is a hexagon around the date compared to a circle that you had in the past.  However, when I run your new code, I do not see the hexagon but instead the circle (see attached image for more details).  I saw on line 639 in the yreport.cls is where you place the circle:

> % Date
> 		\fill[mainColor] (dateCenter)[yshift=1mm] circle (1.8cm);
> 		\fill[Black] (dateCenter)[yshift=1mm] circle (1.4cm); %, draw=Black, ultra thick
> 		\draw[White](dateCenter) node[text width=1.3cm,

How do you change the shape around the date to a hexagon instead?

Thanks!

![Harvey](https://user-images.githubusercontent.com/25627316/68897287-32610b00-06fb-11ea-9279-c9c7cde57fb7.png)

**Comment by HarveySheppard** [comment]
Hey @rbsingh13,

Sorry for not answering earlier (I wasn't notified of your message, don't know why...)

I recompiled the yReport article example and the date appears as an hexagon on my side.
I hope you fixed the problem by yourself in the mean time.
