### ISSUE TITLE
Have caption extend \linewidth in yReport.cls

### ISSUE THREAD

**Issue by rbsingh13** [HarveySheppard/yLaTeX#14]
Hello Harvey, I hope that this message finds your well!

 I have some figures that extend the linewidth of the yReport document.  I wanted to know if there was an easy fix to put the caption to be also \linewidth just for those specific figures?  I am using your latest installment of the yLaTeX-master.  

Excellent work!

**Comment by HarveySheppard** [comment]
Hello rbsingh13,

I am not sure I understand your question exactly. I checked and it seems to me that captions do take the entire `\linewidth` when they contain enough text.

- Normal figures will have their caption take only the width of the text body (not the marginpar)
- Side captions for normal figures will take the width of the whole marginpar
- Side figures will have captions that take the whole marginpar width
- Normal figures with a `centered` environment will take the width of the marginpar and of the text body (see the [example](https://github.com/HarveySheppard/yLaTeX/tree/master/examples/yReport/report) of the yReport class)

Does the above answer your question?
