### ISSUE TITLE
yLectureNote.cls no color or notes showed

### ISSUE THREAD

**Issue by phatsp** [HarveySheppard/yLaTeX#16]
Hi, I am trying the yLectureNote class but then encountered this problem.
```Package pgfkeys Error: I do not know the key '/yMarginDesign/color', to which you passed 'mainColor', and I am going to ignore it. Perhaps you misspelled it. [...nt/.code = {\FlushLeft}, color=mainColor}]```
I looked into the yMarginDesign.sty and see if there was any key named "color" and couldn't find it. When I try to change the last line of code in yLectureNote.cls into one of the available options: "emph color", "text color", it did compile but I then again I see no color or notes.
![image](https://user-images.githubusercontent.com/43247670/86813239-1a833080-c0aa-11ea-88d6-24fee90ceb5e.png)

If you have time, please have a look at this. I would love to create beautiful notes as in your examples.

**Comment by HarveySheppard** [comment]
Hello phatsp,

You are absolutely right, the code in `yLectureNote` is not up to date with the latest version of `yMarginDesign`. I fixed the issue (and a few others). If you try it again, it should work.

**Comment by phatsp** [comment]
Hi, I'm having another trouble using yFlatTable inside yLectureNote. Could you have a look on this? Do I need to open a new issue? 
![image](https://user-images.githubusercontent.com/43247670/88700291-ada40900-d132-11ea-902e-671f9b50289e.png)
![image](https://user-images.githubusercontent.com/43247670/88700369-cad8d780-d132-11ea-8210-518f5887b673.png)
