### ISSUE TITLE
No output PDF file was written -dvipdfmx

### ISSUE THREAD

**Issue by phatsp** [HarveySheppard/yLaTeX#17]
Hi, it's me again. 
I still have trouble compile your example file. This time though it ran normally but didn't invoke any pdf. This is what I get
```dvipdfmx:fatal: pdf_ref_obj(): passed invalid object.

No output PDF file written.

Process exited normally
```
![image](https://user-images.githubusercontent.com/43247670/88458226-c2746880-ceb6-11ea-8262-6430b344b9e1.png)
I tried to solve it myself but don't know how to.
I have miktex installed on windows10.
Sorry for bothering this much.

**Comment by HarveySheppard** [comment]
Hi @phatsp,

No worries. I do not know why you TexStudio is calling `dvipdfmx`. On my side, it calls `xelatex` which generates a PDF. No need to convert from DVI to PDF using `dvipdfmx`.

Can you check you TexStudio configuration? `Options` > `Configure TexStudio` (make sure you have the "Show Advanced Options" button checked) > `Commands` and `Build`.

My xelatex command looks like `xelatex -shell-escape -synctex=1 -interaction=nonstopmode %.tex`. Inside `Build`, my `Build and View` command has just "compile" then "view", `Default Compiler` is set to xelatex and `Default Viewer` is set to `txs:///view-pdf-internal --embedded`.

If TexStudio still does not work, try compiling your document from the command line directly: open a Terminal, move to the directory of the latex file using `cd <path/to/folder>`, then run `xelatex yLectureNoteShowcase.tex`. This will generate a PDF file that you can then look at.

**Comment by phatsp** [comment]
I tried both ways but it still reported the same issue. Even though I have default pdflatex build machine, the already add the ```%!TEX TS-program = xelatex``` on the first line to make sure it is built by xelatex. Here is my configuration.
![image](https://user-images.githubusercontent.com/43247670/88461650-84d00980-cecf-11ea-9c77-1c34897f63c8.png)
![image](https://user-images.githubusercontent.com/43247670/88461690-e5f7dd00-cecf-11ea-9654-9cafaf25b01c.png)

**Comment by HarveySheppard** [comment]
If you have the same problem when executing XeLaTeX from the command line, then there must be a problem with your TeX installation. Can you try installing `epstopdf`? (see https://github.com/yihui/tinytex/issues/161)

**Comment by phatsp** [comment]
Hi, I finally managed to make it work by changing into ```luatex``` instead of ```xelatex```. But I'm not sure if this would produce any errors in the long run if I try using other packages.

Here is what I did so so far:
1. I tried installing ```epstopdf``` but nothing changed. 
2. Then I happened to find [this issue](https://tex.stackexchange.com/questions/334078/xdvipdfmx-pdf-ref-obj-error-with-fontawesome) and [this](https://tex.stackexchange.com/questions/350699/fontawesome-package-not-working-with-xelatex) where they pointed out that the ```fontawesome``` package doesn't work with ```xelatex```. (There are many font warnings in my log files also).
3. I followed some answers and install ```fontawesome``` package on my OS (even though I already have it installed) but still couldn't compile.

The only it works for me right now is to change the building machine to ```luatex```. As I remember, I saw something like ```\newfontfamily{\FA}{fontawesome}``` in some files. You could try looking into this. 
I would love to hear from you should you have any updates on this. 
Also, I'm looking forward to any of your new work.

**Comment by HarveySheppard** [comment]
As I see it, this is really a problem with your XeLaTeX installation. Unfortunately I work on Linux and do not have any Windows machine on which to do some testing.

Regarding the compilation, you can indeed change between LuaLaTeX and XeLaTeX without any problem (only XeLaTeX is generally a bit faster, but I do not use Lua scripting, so both are totally equivalent)

Regarding the font awesome _package_, note that I do not use it. I instead use the _font_ directly. Note that the font should be available for the class to work. If the problem was related to the `fontawesome` package, I would further expect to have similar issues with LuaLaTeX. If you want to check that your XeLaTeX installation is indeed the problem, you could maybe try to compile a very minimal tex document and see if it works.
