### ISSUE TITLE
Have caption across full width of page for \linewidth figure

### ISSUE THREAD

**Issue by rbsingh13** [HarveySheppard/yLaTeX#19]
Hello Harvey,

I have been using your templates for quite a while now for my class assignments and really love your templates.  You have done such a wonderful job with your document!  Thank you for sharing!

I do not typically ask for your help in fixing the aesthetics of the article document, but I have been trying different methods to get the caption to appear across the linewidth of the page only when I have \linewidth figure.  I tried using \linewidth in the caption but that does not work.  Is there a work around you can share with me to have the caption appear across the linewidth only for the linewidth figures in your article template?

I sincerely appreciate your help and want to let you know again that your template is such phenomenal work of art!  I really enjoy using it.

Hope to hear from you soon!

**Comment by HarveySheppard** [comment]
Hi @rbsingh13,

I am very glad to hear that you like and use my templates! I appreciate a lot you telling me!

Could you provide me with some more details on what it is you want to achieve?
What class/package are you using? The article version of `yReport`? Could you also specify what it means to have a caption appear across the linewidth and when you want to enable this behavior?

**Comment by rbsingh13** [comment]
Hello Harvey,

Thanks for your response!  I sincerely appreciate it!

I am mainly using your yReport.cls.

This is an example of what
![2020-11-01_8-24-16](https://user-images.githubusercontent.com/25627316/97804171-11e7d480-1c1c-11eb-99f0-e7796ea54dc0.png)

Thanks again for your quick response!

**Comment by HarveySheppard** [comment]
I believe there is such an [example](https://github.com/HarveySheppard/yLaTeX/blob/master/examples/yReport/report/yReportShowcase.pdf) in the example for `yReport`. The code is as follow:

```latex
\begin{figure}[ht!]
	\begin{centered}
		\includegraphics[width=\linewidth]{<path to your image>}
		\caption{<caption>}
	\end{centered}
\end{figure}
```
