### ISSUE TITLE
Cannot compile "TM_YvesZUMBACH_2014-2015" file

### ISSUE THREAD

**Issue by rbsingh13** [HarveySheppard/yLaTeX#2]
Hello,  Let me begin by saying your work is outstanding!  Thanks for sharing.

I could not compile your "TM_YvesZUMBACH_2014-2015" file found under the TM folder.  I get the error, "\codeTitle undefined".  I looked at your infoBulle.sty file and the command is not there.  I am using WinEDT in the XeLaTeX execution mode.

Note also that I could not get your "yLectureNoteShowcase.tex" to run, as that compilation is complaining about, "Undefined control sequence. l.34 ^^I\nextExerciseSet".

I did get both the article and report to run successfully though.  Thanks!

**Comment by HarveySheppard** [comment]
Hi, Unfortunately, you are right, the "TM_YvesZUMBACH_2014-2015.tex" cannot be compiled anymore (it used an old version of infoBulle that I no longer posses...) I added a note in the README to warn others. Sorry for the inconvenience...

The bug with yLectureNote is now corrected.
