### ISSUE TITLE
Package error "\src@load@hook undefined" after updating Miktex

### ISSUE THREAD

**Issue by rbsingh13** [HarveySheppard/yLaTeX#20]
Hello, after using your article template for quite sometime now, I decided to updated Mikex.  Upon doing so, I get this error: ! Package etoolbox Error: \src@load@hook undefined.
...
l.55renewrobustcmd\scr@load@hook{2]{%..."

I tried rebooting my windows machine, that did not work.
I also renamed the file I was working on, that did not work.

Can you tell me how this can be fixed?

Thanks!

**Comment by HarveySheppard** [comment]
Being myself a Linux user on teX-Live I can only be of  so much help unfortunately... The error above is about internals of `etoolbox` which is rather strange.

Have you compiled the class before with another TeX-distribution then changed your distribution to MiKTex and tried compiling again? If yes, you could try to delete all auxiliary files except the `.tex` (and `.sty` if you have one), then compile again.

**Comment by u-fischer** [comment]
Infobulle.sty loads `interfaces`, a completly outdated package which patches lots of other packages, but hasn't been maintained for nearly 10 years and now breaks.

A simple example for the failure is

~~~~
\documentclass{article}
\usepackage{interfaces}
\begin{document}
aaa
\end{document}
~~~~

**Comment by HarveySheppard** [comment]
I just removed the interface package from `infoBulle`. I hope I was not using it anywhere else.

Thanks @u-fischer for pointing out the outdated package!

**Comment by HarveySheppard** [comment]
I just removed the `interface` package from all my packages (not just the `infoBulle` package). So the entire repo should be clean.
