### ISSUE TITLE
Package etoolbox Error: \src@load@hook undefined

### ISSUE THREAD

**Issue by nescafe-gold** [HarveySheppard/yLaTeX#21]
Compiling gets stuck on /usr/share/texmf-dist/tex/latex/interfaces/interfaces-srcfile.sty
and gives the errors:
- Package etoolbox Error: \src@load@hook undefined
- l.55 \renewrobustcmd*\src@load@hook

**Comment by HarveySheppard** [comment]
Hey @nescafe-gold,
Sorry for not replying earlier, the last weeks were a bit crazy.

This is related to #20 I think, namely the `interface` package is outdated and causing the compilation errors. I just removed the interface package from all my packages, so you should be good to go now.

**Comment by nescafe-gold** [comment]
No need to apologise, I understand. Yeah I found that out before posting so I removed all the times I found the interfaces package in the sty files. It still didn't work so I posted it here but then it started working again the next time I tried it a few hours later.
