### ISSUE TITLE
Cannot compile front page

### ISSUE THREAD

**Issue by Cubba2412** [HarveySheppard/yLaTeX#22]
Hello Harvey!

Hope you are doing well.
I am currently trying to render the front page (titleTwo) og your report template. I've tried to insert the code repo in the online overleaf editor as to have all of the components you have created in one place however when I try to compile it I get the following error:
![image](https://user-images.githubusercontent.com/60875898/112836325-bb7fa480-909a-11eb-9259-8c09b9d7df06.png)

I've created a link so you can see the repo directly online:
https://www.overleaf.com/read/qsxdhjydmbxx

Would you be able to help me debug exactly what is causing this error?

**Comment by HarveySheppard** [comment]
Hey @Cubba2412,

Sorry for replying so late. I tried compiling your overleaf document on my computer by copy-pasting the code and it worked without a problem. The only part I changed is the path to the image so I guess this is your problem.

You could try prefixing the path with `./` or just `/`.

I hope this helps.

**Comment by Cubba2412** [comment]
Hey @HarveySheppard 

I tried to prefix the path with both `./` and `/` however to no avail.
It might be because I'm compiling it in overleaf while you are compiling it locally.

I've created a new link where you can edit in overleaf:
https://www.overleaf.com/7575785858cnsqfmzzdnfk

I would greatly appreciate if you would be able to take a look, so I can use this for one of my assignments at school.

**Comment by HarveySheppard** [comment]
I fixed your issues. The reason the compilation was failing was that fonts were missing. I added all the weights of all the required fonts which is overkill but finding out which fonts are required specifically would have taken a lot of time.

**Comment by HarveySheppard** [comment]
Best of luck with your school assignment!

**Comment by Cubba2412** [comment]
Thank you so much! It compiling now. Really appreciate your assistance. Would love to hand in a Report looking like the beautiful example you have provided.
Out of curiosity, I tried to organise the fonts in a "Fonts" folder. However whenever doing so some specific fonts failed to load (even though I changed to them in the yReport.cls file).
The fonts in the project which are not currently in the Fonts folder in the overleaf I linked above are the ones that fail, when I try to move them to a "Fonts" folder. 
What might be the cause of this issue?

**Comment by HarveySheppard** [comment]
To be honest, I don't fully understand the way XeLaTeX loads fonts. Generally, I compile documents on my own computer, where installing fonts globally is both simpler and cleaner. Making XeLaTeX find local fonts is always a mess. Loading them from a subfolder even more so. That's the reason why in my newer class, I use less fonts so that putting them all at the root of the project is less of an issue. I.e. I hack my way until it works and don't think too much about it.
