### ISSUE TITLE
Change main language

### ISSUE THREAD

**Issue by MAlexGR** [HarveySheppard/yLaTeX#23]
Hello and  thank you for your beautiful templates/packages.

I'd like to ask how can i change the main language to greek (yReport). I  see you are using few `if` switches to catch the language but i'm not sure how they work. Is there a simpler way to change default language (I mainly use `XeLaTeX`  with `Polyglossia` and `fontspec`).

Thanks in advance
Alex

**Comment by HarveySheppard** [comment]
Hey Alex! Sorry for replying so late, I was on holidays.

The `if`s in the `yReport` class are mostly mistakes IMO. I just never got the time to change this. To change the default language use the regular polyglossia commands: `\setdefaultlanguage{greek}`. This should change strings like "Table of Content" etc.

I think this is all you will need to change the language but do not hesitate to send another message if there is something else you need

**Comment by MAlexGR** [comment]
Hello Harvey and thank you for your reply.

I solved the problem by inserting a new if to ```yReport.cls``` :
 ```
\newif\ifGreek
\Greekfalse
\DeclareOption{greek}{
	\Greektrue
	\PassOptionsToClass{greek}{report}
}
```
thought I still don't know how these (if's) works.

Using the "traditional" way with polyglossia:

```
\setdefaultlanguage{greek}
\setotherlanguages{english}

```
and ```fontspec``` package, gave me some strange errors when I was trying to use glossaries package. I don't have time now to investicate the cases so I choose the above if.

Your work with yLaTeX is excellent, thought (IMHO) it needs better documentation. Users can't get the best off from your work without dive deep in source code. I thing a more extensive documentation will fill this gap.

Again, bravo!

I consider this issue closed. Alex

**Comment by HarveySheppard** [comment]
Glad that you could solve your issue!

I totally agree that some more documentation is needed and will hopefully add some when I have a bit of time :sweat_smile: !

Thanks for using this code!
