### ISSUE TITLE
Can't compile yLectureNoteShowcase: fonttitle not defined

### ISSUE THREAD

**Issue by tobiasBora** [HarveySheppard/yLaTeX#24]
First, thanks a lot for this great looking set of libraries (maybe you should publish them on CTAN?).

So I tried to compile the `examples/yLectureNote/yLectureNoteShowcase.tex` by using:
```
latexmk yLectureNoteShowcase.tex
```
after creating the following `latexmkrc` file in this same directory (I copied yLaTeX in the `/tmp` folder):
```
ensure_path('TEXINPUTS', '/tmp/yLaTeX/yPackages//' );
ensure_path('TEXINPUTS', '/tmp/yLaTeX/yClass//' );
$pdf_mode = 1;
$pdflatex = 'lualatex';
```
Unfortunately, I get an error:
```
! Undefined control sequence.
\titlepageTitleStyle ...pt}\selectfont \titleFont 
                                                  #1\endgroup 
l.17 
```
Would it be possible to fix this example so that we can compile it directly?

Thanks!

**Comment by tobiasBora** [comment]
Oups, actually I just noticed that I made a stupid mistake, by commenting the wrong file ^^'

So maybe I can ask another question: how can I redefine the font in `yLectureNote` if I don't have the appropriate font installed on my system?

**Comment by HarveySheppard** [comment]
Publishing on CTAN involves a level of maintenance that I do not want to provide at the moment. Maybe one day ;-)

**Comment by HarveySheppard** [comment]
The first option is to make the font available. To do that, you can install them globally on your computer, or you can put the font files in the folder of your latex document.

**Comment by tobiasBora** [comment]
Thanks. I was just curious to see if there were a way to change the font without modifying the class file (typically people don't like to modify library's code as it defeats the purpose of using a library and impose a maintenance burden). Anyway, I guess it's not too much of an importance here since it's not published. Thanks a lot!
