### ISSUE TITLE
Compile error on subsubsection

### ISSUE THREAD

**Issue by dcrabs** [HarveySheppard/yLaTeX#5]
Hi
I get a compile error on \subsubsection{} in the code below:
Undefined control sequence. \subsubsection{subsubsection}

```
\documentclass[]{yLectureNote}
\title{David}
\begin{document}
    \chapter{chapter}
    \section{section}
    \subsection{subsection}
    \subsubsection{subsubsection}
\end{document}
```

**Comment by HarveySheppard** [comment]
I must admit I am really surprised. On my computer, your code worked just fine! Are you sure you have all necessary fonts installed and visible for LaTeX?
